spring.application.name=hospital
spring.datasource.url=jdbc:postgresql://localhost:5432/hmis
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#server.port=8081
server.address=192.168.1.183
#server.address=192.168.11.48

app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app.jwt-expiration-milliseconds=604800000

